// Shared visible copy and structured-data content. Keep claims tied to published sources.
export const marketSearch = {
  title: 'Business Loan, Hiring & Pricing Decisions | Market Signals | RE IMAGE',
  description: 'Compare economic indicators for small-business loan, hiring, and pricing decisions. Track interest rates, labor costs, inflation, fuel, and projected M2 growth.',
  reviewed: '2026-10-06',
  topics: ['Small business loan decisions', 'Small business hiring decisions', 'Small business pricing decisions', 'Business cost pressure', 'M2 money supply growth'],
  decisions: [
    {
      id: 'business-loan-decisions', label: 'Borrowing & cash flow', title: 'What should I check before taking a business loan?',
      answer: 'Start with the payment your business can support, then use interest-rate trends as context. Compare the lender’s quoted rate, fees, repayment schedule, and total borrowing cost with cash available after operating expenses and existing debt payments.',
      signals: 'Watch interest rates and the operating-cost indicators. A falling federal funds rate does not guarantee a lower business-loan offer, and the pressure score does not measure creditworthiness.',
      action: 'Prepare a base cash-flow forecast and a slower-sales scenario. Include the new payment in both, and review the assumptions with your lender or accountant.',
      link: '/business-funding.html', linkLabel: 'Explore business funding readiness',
      source: 'https://www.sba.gov/loans/', sourceLabel: 'SBA: business loans and repayment eligibility'
    },
    {
      id: 'small-business-hiring-decisions', label: 'Staffing & capacity', title: 'Can my small business afford to hire another employee?',
      answer: 'Compare the full added employment cost with the work and revenue the role can realistically support. Include wages, employer costs, benefits, recruiting, training, and the time before a new hire reaches normal productivity.',
      signals: 'Use the labor-cost indicator to understand national wage trends, then check local pay for the actual role. Consumer prices and sentiment add demand context; your bookings, backlog, and cash flow show what your business can sustain.',
      action: 'Estimate the monthly cost of the role and the additional contribution after variable costs it could create. Test whether you can carry that cost during a slower month.',
      link: '/website-development.html', linkLabel: 'Connect staffing and business operations',
      source: 'https://www.bls.gov/ces/', sourceLabel: 'BLS: employment, hours, and earnings data'
    },
    {
      id: 'small-business-pricing-decisions', label: 'Pricing & margins', title: 'When should a small business review its prices?',
      answer: 'Review pricing when your own labor, supplier, delivery, or financing costs change enough to affect margins. Use PPI, fuel, wages, and CPI to understand the wider environment, then calculate costs for the product or service you actually sell.',
      signals: 'Producer prices, fuel, and labor help explain cost movement. CPI and sentiment provide customer-demand context. M2 is a separate money-supply signal, not a percentage to add automatically to your prices.',
      action: 'Compare contribution per sale before and after a proposed change. For a single product, break-even units equal fixed costs divided by selling price minus variable cost per unit, provided the contribution per unit is positive.',
      link: '/start-with-us.html', linkLabel: 'Discuss a cost and margin dashboard',
      source: 'https://www.sba.gov/counseling/plan-your-business/', sourceLabel: 'SBA: business planning and break-even analysis'
    }
  ],
  faqs: [
    ['Which economic indicators help with small-business loan decisions?', 'Interest rates provide borrowing-cost context, while labor, producer prices, and fuel show pressures on operating cash flow. Compare those signals with actual lender terms, existing debt payments, and your own cash-flow forecast. This dashboard does not determine loan eligibility.'],
    ['How can market data help with hiring decisions?', 'Use wage trends to inform the cost assumptions in a hiring budget, then compare them with local compensation, expected workload, and available cash. National labor data cannot tell you whether one specific role will pay for itself.'],
    ['How do inflation and supplier costs affect pricing decisions?', 'Rising input costs can reduce contribution per sale if your selling price stays fixed. Review actual invoices, payroll, and delivery costs before testing a price change. Customer demand and competitors also matter; an inflation reading is not an automatic price-increase rule.'],
    ['Does the M2 projection predict inflation or tell me how much to raise prices?', 'No. M2 measures money supply, while CPI measures consumer prices. RE IMAGE extends current-year M2 growth at a linear pace and includes it at 25% of the pressure model. That projection is neither a CPI forecast nor a recommended price increase.'],
    ['Is the Market Signals dashboard only for Hartford businesses?', 'The dashboard is published by Hartford-based RE IMAGE for small-business owners in Connecticut and across the United States. Its economic series are national. Use local conditions and your own business figures alongside them.'],
    ['How often is the small-business economic data updated?', 'The data pipeline checks FRED and BLS every 12 hours. Observation dates vary by series and are displayed separately from the refresh time. Missing required inputs make the pressure score unavailable, and a notice appears after 48 hours without a refresh.']
  ]
};

export const locationFilters = [
  { slug: 'hartford', name: 'Hartford', title: 'Hartford, CT Local Businesses', description: 'Explore Hartford restaurants, juice bars, hair braiding, car audio, printing, property services, and community organizations. Check each profile for its storefront or service area.' },
  { slug: 'west-hartford', name: 'West Hartford', title: 'West Hartford, CT Local Businesses', description: 'Find businesses listed for West Hartford, including auto body repair and towing. Compare service details and follow official links for estimates and availability.' },
  { slug: 'east-hartford', name: 'East Hartford', title: 'East Hartford, CT Business Services', description: 'Browse businesses serving East Hartford, including custom printing, apparel, and property services. Profiles distinguish service areas from storefront addresses.' },
  { slug: 'manchester', name: 'Manchester', title: 'Manchester, CT Local Businesses', description: 'Explore businesses listed in Manchester, including skincare and esthetics. Read specialties and use official business links to confirm consultations and appointment availability.' },
  { slug: 'farmington', name: 'Farmington', title: 'Farmington, CT Local Businesses', description: 'Find businesses listed for Farmington, including car rentals. Check vehicle options through the provider and confirm current availability, pricing, and pickup details.' },
  { slug: 'other-connecticut', name: 'Other Connecticut', title: 'More Connecticut Businesses & Services', description: 'Explore businesses with additional Connecticut locations or service areas, including Wethersfield and Clinton. Check individual profiles for the precise areas and services offered.' },
  { slug: 'beyond', name: 'Beyond Greater Hartford', title: 'Businesses Beyond Greater Hartford', description: 'Explore RE IMAGE directory listings outside Greater Hartford, including New York auto services and private transportation, plus a Chicago-based healthcare initiative.' }
];

export const categoryTopics = {
  'car-audio-detailing': { heading:'Car audio installation, electronics & detailing', terms:['car audio installation','auto electronics repair','auto detailing','car electrical installation'], copy:'Looking for car audio installation or auto detailing around Hartford? Compare the listed services, store locations, and appointment options. Describe your vehicle and the work you need when contacting the shop so it can confirm compatibility, timing, and an estimate.' },
  'medical-healthcare': { heading:'Physician collaboration & medical education', terms:['physician collaboration','medical education','healthcare partnerships'], copy:'Explore the healthcare initiatives represented in this directory, including physician collaboration, teaching, and hospital partnerships. These listings describe organizations and participation opportunities. Check the official website to understand the initiative’s scope and how to inquire.' },
  'restaurants-drinks': { heading:'Hartford restaurants, takeout, juice bars & drinks', terms:['Hartford restaurants','Jamaican food','Caribbean takeout','Mexican fusion','juice bars','smoothies'], copy:'Find Hartford food and drink options by the meal or specialty you want: Jamaican and Caribbean favorites, Mexican fusion, fresh juice, smoothies, and takeout. Browse the businesses below, then open their official menus for current dishes, ordering options, and hours.' },
  'nightlife-events': { heading:'Hartford nightlife, cocktails & private events', terms:['Hartford nightlife','cocktail bars','private events','live entertainment'], copy:'Planning a night out or a private gathering in Hartford? Explore the listed venues and their event information. Confirm the current entertainment schedule, group arrangements, food and drink options, and reservation details directly with the venue.' },
  'auto-body-towing': { heading:'Auto body repair, collision estimates & towing', terms:['auto body repair','collision repair','towing services','car paint repair'], copy:'Compare auto body and towing businesses by the work your vehicle needs and the area the shop serves. Use the profile links to ask about collision estimates, paint work, mechanical service, or towing. Connecticut and New York listings are labeled separately so you can choose the right location.' },
  'car-rentals': { heading:'Car rentals, SUVs & passenger vans near Hartford', terms:['car rentals near Hartford','Farmington car rentals','SUV rentals','passenger van rentals'], copy:'Explore a local vehicle-rental option for daily travel, group trips, or a larger vehicle. Follow the rental company’s booking link to confirm available cars, SUVs, trucks, or passenger vans for your dates. Rates, deposits, pickup arrangements, and driver requirements come from the provider.' },
  'skincare-esthetics': { heading:'Skincare, facials & esthetics near Hartford', terms:['Manchester skincare','esthetician near Hartford','customized facials','acne skincare','hyperpigmentation skincare'], copy:'Explore a Manchester skincare business offering customized and corrective skincare. Read the profile for its specialties, then contact the provider about consultations and the services available for your concerns. The directory does not diagnose skin conditions or promise treatment outcomes.' },
  'hair-braiding': { heading:'African hair braiding & protective styles in Hartford', terms:['African hair braiding Hartford','protective hairstyles','twists','locs','hair extensions'], copy:'Find an African hair-braiding business in Hartford and explore protective styles, twists, locs, and extensions. Bring your preferred style, hair length, and timing to the booking conversation. Confirm service duration, hair requirements, and the final price with the stylist.' },
  'printing-apparel': { heading:'Custom printing, embroidery & business apparel', terms:['custom printing Hartford','custom apparel','embroidery','business uniforms','signs and banners'], copy:'Compare printing and custom-apparel options for business uniforms, events, signs, banners, and promotional products. Prepare your artwork, quantity, sizes, and deadline before requesting a quote. Ask the provider about proofs, production timing, and pickup or delivery.' },
  'real-estate-rentals': { heading:'Residential rentals, commercial space & property services', terms:['Hartford property rentals','East Hartford rentals','commercial rentals','property management'], copy:'Explore a property business serving Hartford, East Hartford, and Clinton. Use the official website for current residential or commercial availability and property-management inquiries. This directory describes the business; it does not represent a live inventory of vacant properties.' },
  'community-family': { heading:'Hartford-area community & family resources', terms:['Hartford community resources','family support','mentorship','community gatherings'], copy:'Explore a Hartford-area and online community organization focused on mentorship, gatherings, and resources. Read its profile to understand the activities described, then contact the organization for current participation opportunities, schedules, and availability.' },
  'private-transportation': { heading:'Private chauffeur, airport & corporate transportation', terms:['private chauffeur New York Capital Region','airport transportation','corporate car service','private event transportation'], copy:'Find a private-transportation provider serving New York’s Capital Region. Explore airport, corporate, event, and long-distance ride options, then request availability for your route and date. This listing is outside Greater Hartford and is labeled accordingly.' }
};
